sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1                     # Stops GCloud Installation prompts
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;   # Install GCloud SDK
    - source $HOME/google-cloud-sdk/path.bash.inc             # Source the required Config for GCloud SDK
    - gcloud components update kubectl                        # Install Kubectl
    - gcloud auth activate-service-account --key-file service-account.json  # Authenticate to GCloud
    - gcloud config set project multi-k8s-277308              # Connect to GCloud project using Project ID
    - gcloud config set compute/zone asia-south1-b  # Select the GCloud Zone where your k8s Cluster is running.
    - gcloud container clusters get-credentials multi-cluster # Name of the Kubernetes Cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  # Login to Docker Hub
    - docker build -t sujeetkp/react-test -f ./client/Dockerfile.dev ./client   # Build Client image for Testing

script:
    - docker run -e CI=true sujeetkp/react-test npm run test

deploy:
    provider: script                                           # A custom script will be executed for deployment
    script: bash ./deploy.sh      # "deploy.sh" is the Custom script which contains all the Deployment steps
    on:
        branch: master                                         # If "Master" branch is updated then Deploy.
