sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - export CLOUDSDK_CORE_DISABLE_PROMPTS=1                  # Stops GCloud Installation prompts
    - curl https://sdk.cloud.google.com | bash > /dev/null;   # Install GCloud SDK
    - source $HOME/google-cloud-sdk/path.bash.inc             # Source the required Config for GCloud SDK
    - gcloud components update kubectl                        # Install Kubectl
    - gcloud auth activate-service-account --key-file service-account.json  # Authenticate to GCloud

