apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:                            # Defines the Access Mode (ReadWriteOnly, ReadOnlyMany, ReadWriteMany). It's an array.
        - ReadWriteOnce                     
    resources:                              # Resources available for the Pod to take
        requests:
            storage: 2Gi                    # 2Gi of Volume Spcace is available and can be claimed by the Pod.
                                            # When this PVC is attached to a Pod, Kubernetes provisions a Persistent Volume
                                            # of space 2Gi.
