apiVersion: cert-manager.io/v1alpha2                 # Reaches Cert Manager API Version
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory    # Public API exposed by LetsEncrypt
        email: "padhisujeetku@gmail.com"
        privateKeySecretRef:
            name: letsencrypt-prod                                # We dont have to create this secret manually.
        solvers:
            - http01:
                ingress:
                    class: nginx
                    